import * as exam from './exam.controller.js'
import * as student from './student.controller.js'
import * as employee from './employee.controller.js'
import * as subject from './subject.controller.js'
import * as classroom from './classroom.controller.js'
import * as question from './question.controller.js'
import * as lesson from './lesson.controller.js'
import * as quiz from './quiz.controlller.js'
import * as act from './act.controller.js'
export {student, employee, exam, subject, classroom, question, lesson, quiz, act}